### ISSUE TITLE
Mobile Issues

### ISSUE THREAD

**Issue by AnthonyEvancho** [kevinberonilla/centennial-vision#14]
First round of mobile troubleshooting, mostly reviewed on an iPhone 6:

01: Home logo and text is off-center.
![01](https://cloud.githubusercontent.com/assets/5150542/16155756/7f4dc71a-3476-11e6-996d-a187428e50b5.png)

02: Multiple instances of play button in the background where videos exist.
![02](https://cloud.githubusercontent.com/assets/5150542/16155757/7f4df96a-3476-11e6-97f3-8de54c90f88d.png)

03: When the image is selected here, the text vanishes - on secondary click it does on reveal the hidden text.
![03](https://cloud.githubusercontent.com/assets/5150542/16155760/7f502a50-3476-11e6-935e-c0ac79e8c32b.png)

04: Would it be possible for one swipe event to pull the next image, like a swipe hijack instead of a liner scroll (let me know if this makes sense). 
![04](https://cloud.githubusercontent.com/assets/5150542/16155758/7f4defa6-3476-11e6-8fa9-3ce68ef2d3a8.png)

05: This is taken from an iPhone 5 - the overlay to turn the screen appears on portrait.
![06](https://cloud.githubusercontent.com/assets/5150542/16156074/f815d5c4-3477-11e6-9eb9-0890e311e81e.jpg)

Let me know if this is helpful (including screenshots etc).

**Comment by kevinberonilla** [comment]
Is this the same test site that was used last time? If so can you confirm that browser cache isn't the culprit for the play button issue? I recall fixing this before and I don't know why it's back.

**Comment by kevinberonilla** [comment]
Never mind, I was able replicate these with xcode. The play button issue has been fixed in the newest commit but the others remain unfixed.
