### ISSUE TITLE
(POST-LAUNCH) (BUG) Chrome - the vignette glitches out on resizing to larger windows

### ISSUE THREAD

**Issue by AnthonyEvancho** [kevinberonilla/centennial-vision#27]
I fount that this is likely being caused by the increment of the box shadow being VW, when i change it to pixels it works fine. I'm thinking a box shadow can only render at certain sizes or ratios? 

See below screenshots: 

![screen shot 2016-07-14 at 9 46 41 am](https://cloud.githubusercontent.com/assets/5150542/16843989/0b9989b0-49a9-11e6-99ff-444816541059.png)
![screen shot 2016-07-14 at 9 46 36 am](https://cloud.githubusercontent.com/assets/5150542/16843990/0b9e4f86-49a9-11e6-8a3d-3443aa133906.png)

**Comment by kevinberonilla** [comment]
I have a potential fix for this that doesn't get rid of viewport units (we want to keep them to cover most devices). I'm about to commit some hot stuff along with this fix.
