### ISSUE TITLE
(URGENT) (Fix) iPad - Drop down menu crashes site

### ISSUE THREAD

**Issue by AnthonyEvancho** [kevinberonilla/centennial-vision#30]
The dropdown menu is crashing the site, unclear what is causing this, no error code - just a 'something went wrong' See below for screenshot. 

Maybe just hide the hamburger for tablet and below for now? 

( Notice the sick Borderlands tabs haha )

![img_0299](https://cloud.githubusercontent.com/assets/5150542/16855330/6f90de06-49da-11e6-96ce-7e238996ec44.PNG)

**Comment by kevinberonilla** [comment]
Unfortunately I don't have an iPad, nor can I install Chrome on Xcode Simulator. Some of my other fixes might have alleviated this. Can you please test this first thing tomorrow after my morning commit and let me know if it's still crashing?

**Comment by kevinberonilla** [comment]
This has been turned off for now; it was on your `custom.css` file and I've included it into my Sass workflow.

**Comment by kevinberonilla** [comment]
Closing this for now and making a new issue for this as an enhancement now that we have it disabled on mobile.
